name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Harder, Better, Faster, Stronger
        run: |
          sudo /usr/bin/bash -c 'echo ''set man-db/auto-update false'' | debconf-communicate'
          sudo dpkg-reconfigure man-db

      - name: Set up Qemu and dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y qemu-system-misc qemu-system-x86 qemu-user-static qemu-kvm \
            genisoimage

          sudo modprobe kvm
          sudo chown $(whoami) /dev/kvm

          qemu-system-x86_64 --version

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.7'
          bundler-cache: true

      - name: Print arch info
        run: |
          set -eux
          uname -m
          uname -a
          lsb_release -a

      - name: Setup localruby
        run: |
          set -eux
          curl -fsSL -o guest-support/localruby.tzst http://xb1-p.us-east-1.linodeobjects.com/localruby/localruby.tzst

      - name: Cache base VM image
        uses: actions/cache@v4
        with:
          path: ~/.vemu/base-images
          key: vemu-1

      - name: Fetch ubuntu image
        run: |
          set -eux
          mkdir -p ~/.vemu/base-images
          if [ ! -f ~/.vemu/base-images/ubuntu-amd64.img ]; then
            # time curl -fsSL -o ~/.vemu/base-images/ubuntu-amd64.img https://cloud-images.ubuntu.com/releases/noble/release-20250704/ubuntu-24.04-server-cloudimg-amd64.img
            time curl -fsSL -o ~/.vemu/base-images/ubuntu-amd64.img https://mirrorservice.org/sites/cloud-images.ubuntu.com/releases/noble/release-20250704/ubuntu-24.04-server-cloudimg-amd64.img
          fi

      - name: Run experiment
        run: bin/experiment-qemu

      - name: Print serial log
        run: |
          echo "Cloud init:"
          cat ~/.vemu/vms/early/cloud-init.yaml

          echo "Serial log:"
          cat ~/.vemu/vms/early/serial.log
