name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Harder, Better, Faster, Stronger
        run: |
          sudo /usr/bin/bash -c 'echo ''set man-db/auto-update false'' | debconf-communicate'
          sudo dpkg-reconfigure man-db

      - name: Set up Qemu
        run: |
          sudo apt-get update -y
          sudo apt-get install -y qemu-system qemu-user-static qemu-kvm

          qemu-system-x86_64 --version

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.7'
          bundler-cache: true

      - name: Print arch info
        run: |
          set -eux
          uname -m
          uname -a
          lsb_release -a

      - name: Setup localruby
        run: |
          set -eux
          curl -fsSL -o guest-support/localruby.tzst http://xb1-p.us-east-1.linodeobjects.com/localruby/localruby.tzst

      - name: Run experiment
        run: bin/experiment-qemu
